---
- name: Setup New System
  hosts: localhost

  tasks:
    - name: Clone fzf-git.sh
      ansible.builtin.git:
        repo: "https://github.com/junegunn/fzf-git.sh.git"
        dest: "$HOME/fzf-git.sh"
    - include_tasks: ./tasks/brew.yaml
    - include_tasks: ./tasks/dotfiles.yaml
