- name: Update package lists and install prerequisites
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - build-essential
    - curl
    - file
    - git
    - ruby
    - ruby-dev
    - i3
    - polybar
    - picom
    - rofi
    - alacritty
  tags:
    - basic
