- name: Open Some brew taps
  community.general.homebrew_tap:
    name: "{{ item }}"
  with_items:
    - FelixKratz/formulae
    - homebrew/services
    - koekeishiya/formulae
    - mongodb/brew
    - oven-sh/bun

- name: Install CLI tools
  community.general.homebrew:
    name: "{{ item }}"
    force_formula: true
    state: latest
  with_items:
    - bat
    - chafa
    - fd
    - btop
    - oven-sh/bun/bun
    - deno
    - eza
    - fastlane
    - felixkratz/formulae/sketchybar
    - fzf
    - git
    - git-delta
    - gitleaks
    - gofumpt
    - golangci-lint
    - helm
    - htop
    - jq
    - minikube
    - mas
    - mongodb/brew/mongodb-database-tools
    - neovim
    - node
    - onefetch
    - ranger
    - ripgrep
    - rust
    - starship
    - stow
    - tmux
    - tlrc
    - wget
    - xcbeautify
    - yarn
    - zoxide
    - zsh

- name: Install GUI apps (casks)
  community.general.homebrew_cask:
    name: "{{item}}"
    state: latest
  with_items:
    - nikitabobko/tap/aerospace
    - alacritty
    - android-file-transfer
    - anydesk
    - orbstack
    - font-meslo-lg-nerd-font
    - font-jetbrains-mono-nerd-font
    - font-sf-pro
    - ghostty
    - karabiner-elements
    - google-chrome
    - protonvpn
    - raycast
    - royal-tsx
    - sf-symbols
    - termius
    - tor-browser
    - twingate
    - zed
    - zen-browser
    - whatsapp
    - wezterm

- name: Install Mac App Store
  community.general.mas:
    id: "{{item}}"
    state: latest
  with_items:
    - 409201541
    - 497799835
    - 571213070
    - 409183694
    - 409203825
    - 1527554407
