- name: Install Linuxbrew
  become: false
  become_user: vinay
  shell: |
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    (echo; echo 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"') >> /home/vinay/.bashrc
    eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
  tags:
    - brew
    - zsh
    - ranger
    - tmux
    - neovim
- name: Install software using Linuxbrew
  become: false
  become_user: vinay
  shell: /home/linuxbrew/.linuxbrew/bin/brew install {{ item }}
  loop:
    - fzf
    - neovim
    - tmux
    - eza
    - zoxide
    - btop
    - tlrc
    - rg
    - ranger
    - zsh
    - minikube
    - kubectl
    - helm
    - git-delta
  tags:
    - brew
    - zsh
    - ranger
    - tmux
    - neovim
