- name: Install Linuxbrew
  become: false
  shell: |
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
    git clone https://github.com/junegunn/fzf-git.sh.git
    mv fzf-git.sh ~
  tags:
    - brew
    - zsh
    - ranger
    - tmux
    - neovim
- name: Install software using Linuxbrew
  become: false
  shell: /home/linuxbrew/.linuxbrew/bin/brew install {{ item }}
  loop:
    - fzf
    - xh
    - doggo
    - neovim
    - tmux
    - starship
    - eza
    - zoxide
    - btop
    - tlrc
    - rg
    - ranger
    - zsh
    - minikube
    - kubectl
    - helm
    - git-delta
    - rustfmt
    - rust-analyzer
    - go
    - golangci-lint
    - gofumpt
    - superfile
    - posting
    - harlequin
  tags:
    - brew
    - zsh
    - ranger
    - tmux
    - neovim
