- name: Open Some brew taps
  shell: brew tap {{ item }}
  with_items:
    - FelixKratz/formulae
    - homebrew/services
    - koekeishiya/formulae

- name: Install CLI tools
  shell: brew install {{ item }}
  with_items:
    - bat
    - btop
    - deno
    - eza
    - fastlane
    - sketchybar
    - fzf
    - git-delta
    - gofumpt
    - golangci-lint
    - helm
    - htop
    - jq
    - minikube
    - neovim
    - node
    - onefetch
    - ranger
    - ripgrep
    - starship
    - stow
    - tmux
    - tlrc
    - wget
    - xcbeautify
    - yarn
    - zoxide
    - zsh

- name: Install GUI apps (casks)
  shell: brew install --cask {{ item }}
  with_items:
    - nikitabobko/tap/aerospace
    - alacritty
    - android-file-transfer
    - anydesk
    - docker
    - font-meslo-lg-nerd-font
    - font-jetbrains-mono-nerd-font
    - font-sf-pro
    - google-chrome
    - protonvpn
    - raycast
    - royal-tsx
    - sf-symbols
    - termius
    - tor-browser
    - zed
    - zen-browser
    - whatsapp
