- name: Install software using Linuxbrew
  become: false
  become_user: vinay
  shell: /home/linuxbrew/.linuxbrew/bin/brew install {{ item }}
  loop:
    - stow
  tags:
    - brew
    - stow

- name: Stow Dotfiles
  become: false
  become_user: vinay
  shell: |
    cd dotfiles
    git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
    /home/linuxbrew/.linuxbrew/bin/stow -t ~ *
  tags:
    - brew
    - stow
