- name: Install software using Linuxbrew
  shell: brew install {{ item }}
  loop:
    - stow

- name: Stow Dotfiles
  shell: |
    cd dotfiles
    git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
    stow --adopt -t ~ *
