general.import = [
    "~/.config/alacritty/themes/themes/github_dark_high_contrast.toml"
]
[env]
TERM = "xterm-256color"

[window]
padding = { x = 5, y = 0 }
decorations = "Buttonless"
opacity = 0.8
option_as_alt = "Both"
blur = true

[selection]
save_to_clipboard = true

[font]
normal.family = "JetBrainsMono Nerd Font Mono"
normal.style = "Italic"
size = 21.1
