#!/bin/bash

session=$(find -L   ~ ~/.config ~/.tmux ~/Desktop ~/Downloads ~/Documents -path ~/Library -prune -o -mindepth 1 -maxdepth 4 -type d  | fzf)
session_name=$(basename "$session" | tr . _)


if [ "$TMUX" != "" ]; then 
  if ! tmux has-session -t "$session_name" 2> /dev/null; then
    tmux -u new-session -s "$session_name" -c "$session" -n "editor" -d
  fi
  tmux switch-client -t "$session_name"
else
  if ! tmux has-session -t "$session_name" 2> /dev/null; then
    tmux -u new-session -s "$session_name" -c "$session" -n "editor" -d
  fi
  tmux -u a -t "$session_name"
fi
