import = [
    "~/.config/alacritty/themes/themes/night_owl.toml"
]
[env]
TERM = "xterm-256color"

[window]
padding = { x = 5, y = 0 }
decorations = "Buttonless"
opacity = 0.8
option_as_alt = "Both"
blur = true

[selection]
save_to_clipboard = true

[font]
normal.family = "MesloLGS Nerd Font Mono"
size = 24.3
