import = [
    "~/.config/alacritty/themes/themes/coolnight.toml"
]
[env]
TERM = "xterm-256color"

[window]
padding = { x = 0, y = 0 }
decorations = "none"
opacity = 0.7
option_as_alt = "Both"

[selection]
save_to_clipboard = true

[font]
normal.family = "MesloLGS Nerd Font Mono"
size = 15.8
