#!/bin/bash

session=$(find ~ ~/Desktop ~/Downloads ~/Documents -mindepth 1 -maxdepth 4 -type d | fzf)
session_name=$(basename "$session" | tr . _)


if [ -n "$TMUX" ]; then 
  if ! tmux has-session -t "$session_name" 2> /dev/null; then
    tmux -u new-session -s "$session_name" -c "$session" -d
  fi
  tmux switch-client -t "$session_name"
else
  if ! tmux has-session -t "$session_name" 2> /dev/null; then
    tmux -u new-session -s "$session_name" -c "$session" -d
  fi
  tmux -u a -t "$session_name"
fi
